//! The third-party notices of the release packages: every crate they
//! contain with its licence texts, and the syntax definitions and themes
//! with their acknowledgements (spec `distribution`).
//!
//! The crates are those `cargo tree` reports for the release build of
//! `gitbull-app` on the targets of the packages. Their licence texts come
//! from the files each crate ships; for a crate that ships none, the text of
//! a licence its expression allows is used, see [`fallback`]. Identical
//! texts are listed once, with every crate that uses them.

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};
use std::process::Command;

use two_face::theme::EmbeddedLazyThemeSet;

/// The targets of the release packages.
pub const TARGETS: [&str; 4] = [
    "x86_64-pc-windows-msvc",
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
    "x86_64-unknown-linux-gnu",
];

/// The crate whose dependencies the packages contain.
const PACKAGE: &str = "gitbull-app";

/// The file, at the root of the repository.
pub const FILE: &str = "THIRD-PARTY-NOTICES.md";

/// The fonts git-bull bundles, each beside a licence text named after its
/// family, such as `Inter-OFL.txt` for `InterVariable.ttf`.
const FONTS: &str = "crates/gitbull-app/assets/fonts";

/// Licence files that a crate keeps in a folder: the fonts egui bundles.
const EXTRA_FILES: &[(&str, &[&str])] = &[(
    "epaint_default_fonts",
    &[
        "fonts/OFL.txt",
        "fonts/UFL.txt",
        "fonts/Hack-Regular.txt",
        "fonts/emoji-icon-font-mit-license.txt",
    ],
)];

const APACHE: &str = include_str!("../../../LICENSE-APACHE");
const MIT: &str = include_str!("../../../LICENSE-MIT");
/// The copyright line of git-bull in [`MIT`], which the authors of a crate
/// take the place of.
const MIT_COPYRIGHT: &str = "Copyright (c) 2026 The git-bull contributors";
const BSL: &str = "Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the \"Software\") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.";

/// A crate of the release build.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct Crate {
    pub name: String,
    pub version: String,
    /// Its licence expression, such as `MIT OR Apache-2.0`.
    pub license: String,
}

impl Crate {
    fn label(&self) -> String {
        format!("{} {}", self.name, self.version)
    }
}

fn root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
}

/// Writes the notices file.
pub fn write() -> Result<(), String> {
    let notices = generate()?;
    let path = root().join(FILE);
    std::fs::write(&path, notices).map_err(|error| format!("{}: {error}", path.display()))
}

/// Fails when the notices file is not what [`write`] would write.
pub fn check() -> Result<(), String> {
    let path = root().join(FILE);
    let current =
        std::fs::read_to_string(&path).map_err(|error| format!("{}: {error}", path.display()))?;
    match difference(&current.replace("\r\n", "\n"), &generate()?) {
        None => Ok(()),
        Some(difference) => Err(format!(
            "{FILE} is out of date; run `cargo xtask notices` and commit it.\n{difference}"
        )),
    }
}

/// Where `new` first differs from `old`, line by line, for a message.
pub fn difference(old: &str, new: &str) -> Option<String> {
    if old == new {
        return None;
    }
    let (old_lines, new_lines): (Vec<&str>, Vec<&str>) =
        (old.lines().collect(), new.lines().collect());
    let at = (0..old_lines.len().max(new_lines.len()))
        .find(|&i| old_lines.get(i) != new_lines.get(i))
        .unwrap_or(0);
    let line = |lines: &[&str]| {
        lines
            .get(at)
            .map_or("(none)".to_owned(), |line| format!("{line:?}"))
    };
    Some(format!(
        "First difference at line {}:\n  file:      {}\n  generated: {}",
        at + 1,
        line(&old_lines),
        line(&new_lines)
    ))
}

/// The notices of the release build, as Markdown.
pub fn generate() -> Result<String, String> {
    let crates = release_crates()?;
    let registries = registries();
    let mut uses: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
    let mut missing = Vec::new();
    for krate in &crates {
        match license_texts(krate, &registries) {
            Ok(texts) => {
                for text in texts {
                    uses.entry(normalize(&text))
                        .or_default()
                        .insert(krate.label());
                }
            }
            Err(message) => missing.push(message),
        }
    }
    if !missing.is_empty() {
        return Err(missing.join("\n"));
    }
    render(&crates, &uses)
}

/// The crates `cargo tree` reports for the release build on every target.
pub fn release_crates() -> Result<Vec<Crate>, String> {
    let cargo = std::env::var("CARGO").unwrap_or_else(|_| "cargo".to_owned());
    let mut crates = BTreeSet::new();
    for target in TARGETS {
        let output = Command::new(&cargo)
            .current_dir(root())
            .args([
                "tree", "--locked", "--color", "never", "-p", PACKAGE, "-e", "normal",
            ])
            .args(["--target", target, "--prefix", "none", "-f", "{p}|{l}"])
            .output()
            .map_err(|error| format!("cargo tree: {error}"))?;
        if !output.status.success() {
            return Err(format!(
                "cargo tree --target {target} failed: {}",
                String::from_utf8_lossy(&output.stderr)
            ));
        }
        crates.extend(
            String::from_utf8_lossy(&output.stdout)
                .lines()
                .filter_map(parse_tree_line),
        );
    }
    Ok(crates.into_iter().collect())
}

/// Reads a line of `cargo tree --prefix none -f "{p}|{l}"`, such as
/// `serde v1.0.228|MIT OR Apache-2.0`. Crates of the workspace, which name
/// their folder, are left out.
pub fn parse_tree_line(line: &str) -> Option<Crate> {
    let (package, license) = line.split_once('|')?;
    let mut parts = package.splitn(3, ' ');
    let name = parts.next()?;
    let version = parts.next()?.strip_prefix('v')?;
    let rest = parts.next().unwrap_or_default();
    // What cargo adds in parentheses: `(*)` for a crate listed before,
    // `(proc-macro)`, or the folder of a crate of the workspace.
    let local = rest
        .split(" (")
        .map(|part| part.trim_start_matches('('))
        .filter(|part| !part.is_empty())
        .any(|part| part != "*)" && part != "proc-macro)");
    if local || name.is_empty() {
        return None;
    }
    // Cargo marks a crate listed before with `(*)` at the end of the line.
    let license = license.trim();
    let license = license.strip_suffix("(*)").unwrap_or(license).trim_end();
    Some(Crate {
        name: name.to_owned(),
        version: version.to_owned(),
        license: license.to_owned(),
    })
}

/// The folders into which cargo unpacks the crates of registries.
fn registries() -> Vec<PathBuf> {
    let home = std::env::var_os("CARGO_HOME")
        .map(PathBuf::from)
        .or_else(|| {
            std::env::var_os("USERPROFILE")
                .or_else(|| std::env::var_os("HOME"))
                .map(|home| PathBuf::from(home).join(".cargo"))
        })
        .unwrap_or_default();
    std::fs::read_dir(home.join("registry").join("src"))
        .map(|entries| entries.flatten().map(|entry| entry.path()).collect())
        .unwrap_or_default()
}

/// Whether a file at the root of a crate holds its licence.
pub fn is_license_file(name: &str) -> bool {
    let name = name.to_ascii_lowercase();
    [
        "license",
        "licence",
        "copying",
        "copyright",
        "notice",
        "unlicense",
    ]
    .iter()
    .any(|start| name.starts_with(start))
}

/// The licence texts of `krate`: the files it ships, else the text of a
/// licence its expression allows; and files it keeps in folders.
fn license_texts(krate: &Crate, registries: &[PathBuf]) -> Result<Vec<String>, String> {
    let folder = format!("{}-{}", krate.name, krate.version);
    let dir = registries
        .iter()
        .map(|registry| registry.join(&folder))
        .find(|dir| dir.is_dir())
        .ok_or_else(|| {
            format!(
                "{} is not unpacked; run `cargo fetch --locked` first",
                krate.label()
            )
        })?;
    let manifest = std::fs::read_to_string(dir.join("Cargo.toml"))
        .ok()
        .and_then(|text| text.parse::<toml::Table>().ok());
    let package = manifest
        .as_ref()
        .and_then(|manifest| manifest.get("package"))
        .and_then(|package| package.as_table());
    let mut files: Vec<PathBuf> = std::fs::read_dir(&dir)
        .map_err(|error| format!("{}: {error}", dir.display()))?
        .flatten()
        .filter(|entry| entry.path().is_file())
        .filter(|entry| is_license_file(&entry.file_name().to_string_lossy()))
        .map(|entry| entry.path())
        .collect();
    if let Some(file) = package
        .and_then(|package| package.get("license-file"))
        .and_then(|file| file.as_str())
    {
        let file = dir.join(file);
        if file.is_file() && !files.contains(&file) {
            files.push(file);
        }
    }
    files.sort();
    let mut texts: Vec<String> = files
        .iter()
        .filter_map(|file| std::fs::read(file).ok())
        .map(|bytes| String::from_utf8_lossy(&bytes).into_owned())
        .collect();
    if texts.is_empty() {
        let authors: Vec<String> = package
            .and_then(|package| package.get("authors"))
            .and_then(|authors| authors.as_array())
            .map(|authors| {
                authors
                    .iter()
                    .filter_map(|author| author.as_str().map(str::to_owned))
                    .collect()
            })
            .unwrap_or_default();
        let text = fallback(&krate.license, &krate.name, &authors).ok_or_else(|| {
            format!(
                "{} ships no licence file, and git-bull has no text for {}",
                krate.label(),
                krate.license
            )
        })?;
        texts.push(text);
    }
    for (name, extra) in EXTRA_FILES {
        if *name == krate.name {
            for file in *extra {
                let bytes = std::fs::read(dir.join(file))
                    .map_err(|error| format!("{} {file}: {error}", krate.label()))?;
                texts.push(String::from_utf8_lossy(&bytes).into_owned());
            }
        }
    }
    Ok(texts)
}

/// The text of a licence that `expression` allows, for a crate that ships
/// no licence file. Apache-2.0 comes first, as its text names no copyright
/// holder; the MIT text names the authors of the crate.
pub fn fallback(expression: &str, name: &str, authors: &[String]) -> Option<String> {
    let ids: Vec<&str> = expression
        .split(|c: char| !(c.is_ascii_alphanumeric() || c == '-' || c == '.'))
        .filter(|id| !id.is_empty())
        .collect();
    if ids.contains(&"Apache-2.0") {
        return Some(APACHE.to_owned());
    }
    if ids.contains(&"MIT") {
        let holders = match authors.is_empty() {
            true => format!("The {name} authors"),
            false => authors.join(", "),
        };
        return Some(MIT.replace(MIT_COPYRIGHT, &format!("Copyright (c) {holders}")));
    }
    if ids.contains(&"BSL-1.0") {
        return Some(BSL.to_owned());
    }
    None
}

/// `text` with line endings and trailing spaces made uniform, so that
/// copies of one licence count as one.
pub fn normalize(text: &str) -> String {
    let lines: Vec<&str> = text.lines().map(str::trim_end).collect();
    let start = lines.iter().position(|line| !line.is_empty()).unwrap_or(0);
    let end = lines
        .iter()
        .rposition(|line| !line.is_empty())
        .map_or(0, |end| end + 1);
    lines[start..end.max(start)].join("\n")
}

/// A fence for `text` in Markdown: longer than any run of backticks in it.
pub fn fence(text: &str) -> String {
    let longest = text.split(|c| c != '`').map(str::len).max().unwrap_or(0);
    "`".repeat(longest.max(2) + 1)
}

fn render(crates: &[Crate], uses: &BTreeMap<String, BTreeSet<String>>) -> Result<String, String> {
    let mut out = String::new();
    out.push_str(
        "# Third-party notices

git-bull is licensed under MIT OR Apache-2.0; see `LICENSE-MIT` and
`LICENSE-APACHE`. Its release packages contain the third-party components
below, each under its own licence.

This file is generated with `cargo xtask notices`. Do not edit it by hand.

",
    );
    render_assets(&mut out);
    render_fonts(&mut out)?;

    out.push_str(&format!(
        "## Rust crates\n\nThe {} crates of the release build on {}.\n\n",
        crates.len(),
        TARGETS.join(", ")
    ));
    out.push_str("| Crate | Version | Licence |\n|---|---|---|\n");
    for krate in crates {
        out.push_str(&format!(
            "| {} | {} | {} |\n",
            krate.name,
            krate.version,
            krate.license.replace('|', "\\|")
        ));
    }
    out.push_str("\n### Licence texts\n\n");
    // Each text once, in the order of the first crate that uses it.
    let mut texts: Vec<(&BTreeSet<String>, &String)> =
        uses.iter().map(|(text, users)| (users, text)).collect();
    texts.sort();
    for (users, text) in texts {
        let users: Vec<&str> = users.iter().map(String::as_str).collect();
        let fence = fence(text);
        out.push_str(&format!(
            "Used by {}:\n\n{fence}text\n{text}\n{fence}\n\n",
            users.join(", ")
        ));
    }
    Ok(out)
}

/// The syntax definitions and themes of two-face, and the acknowledgements
/// their licences ask for.
/// A font git-bull bundles, with its licence text.
#[derive(Debug)]
pub struct Font {
    pub file: String,
    pub licence: String,
}

/// The fonts in [`FONTS`], each with the licence text whose family its
/// file name starts with.
pub fn bundled_fonts() -> Result<Vec<Font>, String> {
    let folder = root().join(FONTS);
    let mut names: Vec<String> = std::fs::read_dir(&folder)
        .map_err(|error| format!("{}: {error}", folder.display()))?
        .filter_map(|entry| entry.ok()?.file_name().into_string().ok())
        .collect();
    names.sort();
    let licences: Vec<&String> = names.iter().filter(|name| name.ends_with(".txt")).collect();
    names
        .iter()
        .filter(|name| name.ends_with(".ttf"))
        .map(|file| {
            let licence = licences
                .iter()
                .find(|licence| {
                    let family = licence.rsplit_once('-').map_or("", |(family, _)| family);
                    !family.is_empty() && file.starts_with(family)
                })
                .ok_or_else(|| format!("{file} has no licence text in {FONTS}"))?;
            let text = std::fs::read_to_string(folder.join(licence))
                .map_err(|error| format!("{licence}: {error}"))?;
            Ok(Font {
                file: file.clone(),
                licence: text,
            })
        })
        .collect()
}

fn render_fonts(out: &mut String) -> Result<(), String> {
    out.push_str("## Fonts\n\ngit-bull bundles these fonts with their licences.\n\n");
    for font in bundled_fonts()? {
        let text = normalize(&font.licence);
        let fence = fence(&text);
        out.push_str(&format!(
            "### {}\n\n{fence}text\n{text}\n{fence}\n\n",
            font.file
        ));
    }
    Ok(())
}

fn render_assets(out: &mut String) {
    let mut syntaxes: Vec<String> = two_face::syntax::extra_newlines()
        .syntaxes()
        .iter()
        .map(|syntax| syntax.name.clone())
        .collect();
    syntaxes.sort();
    syntaxes.dedup();
    let themes: Vec<&str> = EmbeddedLazyThemeSet::theme_names()
        .iter()
        .map(|theme| theme.as_name())
        .collect();
    let listing = two_face::acknowledgement::listing();
    out.push_str(&format!(
        "## Syntax definitions and themes

git-bull bundles the {} syntax definitions and {} themes of the crate
two-face, which come from bat and from Sublime Text packages. The licences
that ask for an acknowledgement follow the lists; the others do not.

Syntax definitions: {}.

Themes: {}.

",
        syntaxes.len(),
        themes.len(),
        syntaxes.join(", "),
        themes.join(", ")
    ));
    for license in listing.for_syntaxes().iter().chain(listing.for_themes()) {
        let text = normalize(&license.text);
        let fence = fence(&text);
        out.push_str(&format!(
            "### {}\n\n{fence}text\n{text}\n{fence}\n\n",
            license.rel_path.display().to_string().replace('\\', "/")
        ));
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn krate(name: &str, version: &str, license: &str) -> Crate {
        Crate {
            name: name.to_owned(),
            version: version.to_owned(),
            license: license.to_owned(),
        }
    }

    #[test]
    fn a_line_of_cargo_tree_names_the_crate_its_version_and_licence() {
        assert_eq!(
            parse_tree_line("serde v1.0.228|MIT OR Apache-2.0"),
            Some(krate("serde", "1.0.228", "MIT OR Apache-2.0"))
        );
        assert_eq!(
            parse_tree_line("serde_derive v1.0.228 (proc-macro) (*)|MIT OR Apache-2.0"),
            Some(krate("serde_derive", "1.0.228", "MIT OR Apache-2.0"))
        );
        assert_eq!(
            parse_tree_line("accesskit v0.24.1|MIT OR Apache-2.0 (*)"),
            Some(krate("accesskit", "0.24.1", "MIT OR Apache-2.0"))
        );
        assert_eq!(
            parse_tree_line("ndk-sys v0.6.0+11769913|MIT OR Apache-2.0"),
            Some(krate("ndk-sys", "0.6.0+11769913", "MIT OR Apache-2.0"))
        );
    }

    #[test]
    fn crates_of_the_workspace_are_left_out() {
        assert_eq!(
            parse_tree_line(
                r"gitbull-core v0.1.0 (C:\work\git-bull\crates\gitbull-core)|MIT OR Apache-2.0"
            ),
            None
        );
        assert_eq!(
            parse_tree_line("gitbull-git v0.1.0 (/work/git-bull/crates/gitbull-git) (*)|MIT"),
            None
        );
        assert_eq!(parse_tree_line(""), None);
    }

    #[test]
    fn licence_files_are_known_by_their_names() {
        for name in [
            "LICENSE",
            "LICENSE-MIT",
            "license.txt",
            "LICENCE.md",
            "COPYING",
            "COPYRIGHT",
            "NOTICE",
            "UNLICENSE",
        ] {
            assert!(is_license_file(name), "{name}");
        }
        for name in ["Cargo.toml", "README.md", "src"] {
            assert!(!is_license_file(name), "{name}");
        }
    }

    #[test]
    fn a_crate_without_licence_files_gets_the_text_of_a_licence_it_allows() {
        let apache = fallback("MIT OR Apache-2.0", "egui", &[]).unwrap();
        assert!(apache.contains("Apache License"));
        assert!(
            fallback("Apache-2.0/MIT", "old", &[])
                .unwrap()
                .contains("Apache License")
        );

        let authors = ["Mads Marquart <mads@marquart.dk>".to_owned()];
        let mit = fallback("MIT", "objc2", &authors).unwrap();
        assert!(mit.starts_with("MIT License\n\nCopyright (c) Mads Marquart <mads@marquart.dk>"));
        assert!(!mit.contains("git-bull"));
        assert!(
            fallback("MIT", "dispatch", &[])
                .unwrap()
                .contains("The dispatch authors")
        );

        assert!(
            fallback("BSL-1.0", "clipboard-win", &[])
                .unwrap()
                .starts_with("Boost Software License")
        );
        assert_eq!(fallback("LGPL-2.1-or-later", "x", &[]), None);
    }

    #[test]
    fn copies_of_one_licence_become_one_text() {
        assert_eq!(
            normalize("\r\n  MIT  \r\nLicense \r\n\r\n"),
            "  MIT\nLicense"
        );
        assert_eq!(normalize(""), "");
    }

    #[test]
    fn a_fence_is_longer_than_any_backticks_in_the_text() {
        assert_eq!(fence("plain"), "```");
        assert_eq!(fence("a ```` b"), "`````");
    }

    fn committed() -> String {
        std::fs::read_to_string(root().join(FILE))
            .expect("the notices file is committed")
            .replace("\r\n", "\n")
    }

    /// Run by hand before a release, like the test that the file is up
    /// to date: an update of a dependency must not block CI.
    #[test]
    #[ignore = "run by hand before a release"]
    fn the_notices_list_every_crate_of_the_release_build() {
        let notices = committed();
        let crates = release_crates().unwrap();
        assert!(crates.len() > 300, "{} crates", crates.len());
        for krate in crates {
            let row = format!("| {} | {} |", krate.name, krate.version);
            assert!(notices.contains(&row), "{} is missing", krate.label());
            assert!(
                notices.contains(&krate.label()),
                "{} has no licence text",
                krate.label()
            );
        }
    }

    #[test]
    fn the_notices_list_every_bundled_syntax_and_theme_with_its_acknowledgement() {
        let notices = committed();
        for syntax in two_face::syntax::extra_newlines().syntaxes() {
            assert!(notices.contains(&syntax.name), "{} is missing", syntax.name);
        }
        for theme in EmbeddedLazyThemeSet::theme_names() {
            assert!(notices.contains(theme.as_name()), "{:?} is missing", theme);
        }
        let listing = two_face::acknowledgement::listing();
        for license in listing.for_syntaxes().iter().chain(listing.for_themes()) {
            assert!(notices.contains(&normalize(&license.text)));
        }
    }

    #[test]
    fn the_notices_list_every_bundled_font_with_its_licence() {
        let notices = committed();
        let fonts = bundled_fonts().unwrap();
        assert!(fonts.len() >= 2, "{fonts:?}");
        for font in fonts {
            assert!(notices.contains(&font.file), "{} is missing", font.file);
            assert!(
                notices.contains(&normalize(&font.licence)),
                "the licence of {} is missing",
                font.file
            );
        }
    }

    /// Run by hand with `cargo test -p xtask -- --ignored` before a
    /// release; out of CI, so that an update of a dependency does not block
    /// it, as licence work comes last.
    #[test]
    #[ignore = "run by hand before a release"]
    fn the_notices_are_up_to_date() {
        if let Some(difference) = difference(&committed(), &generate().unwrap()) {
            panic!("{FILE} is out of date; run `cargo xtask notices` and commit it.\n{difference}");
        }
    }

    #[test]
    fn a_difference_names_its_first_line() {
        assert_eq!(difference("a\nb\n", "a\nb\n"), None);
        let message = difference("a\nb\nc", "a\nx\nc").unwrap();
        assert!(message.contains("line 2"), "{message}");
        assert!(
            message.contains("\"b\"") && message.contains("\"x\""),
            "{message}"
        );
        assert!(difference("a", "a\nb").unwrap().contains("(none)"));
    }
}
