[package]
name = "gitbull-app"
description = "The git-bull desktop application."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[[bin]]
name = "git-bull"
path = "src/main.rs"

[dependencies]
gitbull-core.workspace = true
